title:              onlystar's blog
email:              tjdwls0607@naver.com
description:        Space Only For Me.
author:             onlystar
baseurl:            ""
url:                "https://onlystar.github.io"

# Social Profiles
github_username:    onlystar


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
